### ISSUE TITLE
User Interface Sketch

### ISSUE THREAD

**Issue by cardinalli-uh** [Pine-Line/pine-line.github.io#2]
A baseline sketch of our planned user interface.

**Comment by ramytramit** [comment]
![PineLine Calendaring Mockup](https://user-images.githubusercontent.com/53219044/85992980-58d56d00-b991-11ea-8ea4-4fd4811fe96e.png)

**Comment by ramytramit** [comment]
I can edit this further, but I think this mockup should give a pretty good gist of the interface. 
I'm guessing we'll veer from this a bit, but for an initial concept I think it covers all the features. Final product will look better.

**Comment by cardinalli-uh** [comment]
This is sufficient for now - will create a new issue when/if we decide to reevaluate our UI.

**Comment by cardinalli-uh** [comment]
Note: As of now recurrence functions are not featured in the mockup.
